### ISSUE TITLE
eliminate need for private branch / repo?

### ISSUE THREAD

**Issue by pearsonca** [ICI3D/DAIDD#1]
What purpose does the private master branch serve?

**Comment by jrcpulliam** [comment]
It's where we plan and organize DAIDD. Contains notes and links to lots of stuff that should not be public; please retain as-is

**Comment by pearsonca** [comment]
Is that approach a process *choice* or a *need*?

While the gh-pages get served, there is not in fact a public branch (showing the underlying code), which definitely conflicts with another objective of ICI3D (making organizing resources available).

There are other options available for the coordinating activities you describe - what's the purpose of having them happen in the master branch of this repo? Seems unlikely to be content related - the two branches are massively diverged.

**Comment by jrcpulliam** [comment]
The master branch is not being used (with shift to GD for KM) but I feel should be retained in some way for archival purposes. Still contains notes and links to lots of stuff that should not be public

**Comment by pearsonca** [comment]
has been shifted to daidd-private.
